name: Vigilante Web

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  construir_web:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4 # Actualizado a la versión más moderna
        with:
          fetch-depth: 0 # Descarga todo el historial para evitar errores de subida

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar Robot y Crear Web
        env:
          WHATSAPP_PHONE: ${{ secrets.WHATSAPP_PHONE }}
          WHATSAPP_API_KEY: ${{ secrets.WHATSAPP_API_KEY }}
        run: python robot.py

      - name: Publicar cambios en la web
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m "Actualización automática de la web" || echo "Sin cambios"
          git push origin main
